{
    "version": {
        "version": 76,
        "gb_version": "942_b_510"
    },
    "pairs": {
        "poloniex": {
            "BTC-ETH": {
                "strategy": "emotionless",
                "override": {

                }
            }
        },
        "bittrex": {
            "BTC-ETC": {
                "strategy": "emotionless",
                "override": {

                }
            }
        },
        "kraken": {
            "BTC-ETH": {
                "strategy": "emotionless",
                "override": {

                }
            },
            "BTC-GNO": {
                "strategy": "emotionless",
                "override": {

                }
            },
            "EUR-BTC": {
                "strategy": "emotionless",
                "override": {

                }
            }
        },
        "cryptopia": {
            "BTC-DOGE": {
                "strategy": "emotionless",
                "override": {

                }
            }
        },
        "bitfinex": {
            "BTC-IOT": {
                "strategy": "emotionless",
                "override": {

                }
            }
        },
        "binance": {
            "BTC-IOTA": {
                "strategy": "emotionless",
                "override": {

                }
            }
        },
        "cex": {
            "USD-BTC": {
                "strategy": "emotionless",
                "override": {

                }
            }
        },
        "gdax": {
            "USD-BTC": {
                "strategy": "emotionless",
                "override": {

                }
            }
        }
    },
    "strategies": {
        "emotionless": {
            "NAME": "emotionless",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,

            "SELL_ENABLED": true,
            "GAIN": 0.6,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },
        "bb": {
            "NAME": "bb",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,

            "SELL_ENABLED": true,
            "GAIN": 0.6,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_BUY": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },
        "tsslbb": {
            "NAME": "tsslbb",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,
            "BUY_RANGE": 0.6,

            "SELL_ENABLED": true,
            "GAIN": 0.6,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_BUY": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },
        "gain": {
            "NAME": "gain",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,

            "SELL_ENABLED": true,
            "GAIN": 0.6,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_BUY": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },
            "stepgain": {
            "NAME": "stepgain",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,
            "BUYLVL1": 0.6,
            "BUYLVL2": 2,
            "BUYLVL3": 70,
            "BUYLVL": 2,
                
            "SELL_ENABLED": true,
            "GAIN": 0.6,
            "SELLLVL1": 0.6,
            "SELLLVL2": 2,
            "SELLLVL3": 70,
            "SELLLVL": 2,
                
            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_BUY": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },
        "custom": {
            "NAME": "SMACROSS",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,

            "SELL_ENABLED": true,
            "GAIN": 0.6,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_BUY": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },
        "pp": {
            "NAME": "pp",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,
            "PP_BUY": 12345,

            "SELL_ENABLED": true,
            "GAIN": 0.6,
            "PP_SELL": 12345,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_BUY": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },

        "tsslpp": {
            "NAME": "tsslpp",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,
            "BUY_RANGE": 0.6,

            "SELL_ENABLED": true,
            "GAIN": 0.6,
            "PP_SELL": 12345,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_BUY": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },
        "ichimoku": {
            "NAME": "ichimoku",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,

            "SELL_ENABLED": true,
            "GAIN": 0.6,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_BUY": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },
        "tsslstepgain": {
            "NAME": "tsslstepgain",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,
            "BUY_RANGE": 0.6,

            "SELL_ENABLED": true,
            "GAIN": 0.6,
            "SELLLVL1": 0.6,
            "SELLLVL2": 2,
            "SELLLVL3": 70,
            "SELLLVL": 2,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_BUY": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },
        "tssl": {
            "NAME": "tssl",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,
            "BUY_RANGE": 0.6,

            "SELL_ENABLED": true,
            "GAIN": 0.6,
            "SELL_RANGE": 0.6,
            "TSSL_TARGET_ONLY": true,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "DU_BUYDOWN": 2,
            "AIRDROP": false,

            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },
        "tsslgain": {
            "NAME": "tsslgain",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,
            "BUY_RANGE": 0.6,

            "SELL_ENABLED": true,
            "GAIN": 0.6,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_BUY": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },

        "pptssl": {
            "NAME": "pptssl",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,
            "PP_BUY": 12345,

            "SELL_ENABLED": true,
            "GAIN": 0.6,
            "SELL_RANGE": 0.6,
            "TSSL_TARGET_ONLY": true,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_BUY": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },
        "stepgaintssl": {
            "NAME": "stepgaintssl",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,
            "BUYLVL1": 0.6,
            "BUYLVL2": 2,
            "BUYLVL3": 70,
            "BUYLVL": 2,

            "SELL_ENABLED": true,
            "GAIN": 0.6,
            "SELL_RANGE": 0.6,
            "TSSL_TARGET_ONLY": true,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },
        "gaintssl": {
            "NAME": "gaintssl",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,

            "SELL_ENABLED": true,
            "GAIN": 0.6,
            "SELL_RANGE": 0.6,
            "TSSL_TARGET_ONLY": true,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_BUY": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },
        "bbtssl": {
            "NAME": "bbtssl",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,

            "SELL_ENABLED": true,
            "GAIN": 0.6,
            "SELL_RANGE": 0.6,
            "TSSL_TARGET_ONLY": true,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_BUY": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },

        "bbgain": {
            "NAME": "bbgain",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,

            "SELL_ENABLED": true,
            "GAIN": 0.6,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_BUY": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },
        "gainbb": {
            "NAME": "gainbb",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,


            "SELL_ENABLED": true,
            "GAIN": 0.6,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_BUY": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },
        "bbstepgain": {
            "NAME": "bbstepgain",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,

            "SELL_ENABLED": true,
            "GAIN": 0.6,
            "SELLLVL1": 0.6,
            "SELLLVL2": 2,
            "SELLLVL3": 70,
            "SELLLVL": 2,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_BUY": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },
        "stepgainbb": {
            "NAME": "stepgainbb",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,
            "BUYLVL1": 0.6,
            "BUYLVL2": 2,
            "BUYLVL3": 70,
            "BUYLVL": 2,

            "SELL_ENABLED": true,
            "GAIN": 0.6,
            "SELLLVL1": 0.6,
            "SELLLVL2": 2,
            "SELLLVL3": 70,
            "SELLLVL": 2,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_BUY": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },
        "bbpp": {
            "NAME": "bbpp",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,

            "SELL_ENABLED": true,
            "GAIN": 0.6,
            "PP_SELL": 2,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_BUY": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },
        "ppbb": {
            "NAME": "ppbb",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,
            "PP_BUY": 2,

            "SELL_ENABLED": true,
            "GAIN": 0.6,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_BUY": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },
        "gainstepgain": {
            "NAME": "gainstepgain",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,

            "SELL_ENABLED": true,
            "GAIN": 0.6,
            "SELLLVL1": 0.6,
            "SELLLVL2": 2,
            "SELLLVL3": 70,
            "SELLLVL": 2,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_BUY": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },
        "stepgaingain": {
            "NAME": "stepgaingain",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,
            "BUYLVL1": 0.6,
            "BUYLVL2": 2,
            "BUYLVL3": 70,
            "BUYLVL": 2,

            "SELL_ENABLED": true,
            "GAIN": 0.6,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_BUY": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },
        "gainpp": {
            "NAME": "gainpp",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,

            "SELL_ENABLED": true,
            "GAIN": 0.6,
            "PP_SELL": 123456,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_BUY": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },
        "ppgain": {
            "NAME": "ppgain",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,
            "PP_BUY": 123456,

            "SELL_ENABLED": true,
            "GAIN": 0.6,
            "SELL_RANGE": 0.6,
            "TSSL_TARGET_ONLY": true,
            "SELLLVL1": 0.6,
            "SELLLVL2": 2,
            "SELLLVL3": 70,
            "SELLLVL": 2,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_BUY": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },
        "stepgainpp": {
            "NAME": "stepgainpp",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,
            "BUYLVL1": 0.6,
            "BUYLVL2": 2,
            "BUYLVL3": 70,
            "BUYLVL": 2,

            "SELL_ENABLED": true,
            "GAIN": 0.6,
            "PP_SELL": 2,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_BUY": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        },
        "ppstepgain": {
            "NAME": "ppstepgain",

            "BUY_ENABLED": true,
            "BUY_LEVEL": 0.1,
            "PP_BUY": 123456,

            "SELL_ENABLED": true,
            "GAIN": 0.6,
            "SELLLVL1": 0.6,
            "SELLLVL2": 2,
            "SELLLVL3": 70,
            "SELLLVL": 2,

            "TRADING_FEES": 0.25,
            "TRADING_LIMIT": 0.002,
            "FUNDS_RESERVE": 0.0001,

            "PERIOD": 15,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SLOW_SMA": 1,
            "FAST_SMA": 2,
            "MACD_SHORT": 5,
            "MACD_LONG": 20,
            "MACD_SIGNAL": 10,
            "STOCH_ENABLED": false,
            "STOCH_BUY_LEVEL": 20,
            "STOCH_SELL_LEVEL": 80,
            "STOCH_K": 14,
            "SLOW_STOCH_K": 3,
            "STOCH_D": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "MFI_ENABLED": false,
            "MFI_SELL_LEVEL": 30,
            "MFI_BUY_LEVEL": 70,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,

            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "DU_CAP_COUNT": 0,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 2,
            "RSI_DU_BUY": 30,

            "RT_ENABLED": false,
            "RT_MAXBAG_PROTECTION": 10,
            "RT_BUY_BUYDOWN": 2,
            "RT_SELL_BUYDOWN": 1,
            "AIRDROP": false,

            "TRAIL_ME_SELL": false,
            "TRAIL_ME_BUY": false,
            "TRAIL_ME_RT": false,
            "TRAIL_ME_DU": false,
            "TRAIL_ME_SELL_RANGE": 0.5,
            "TRAIL_ME_BUY_RANGE": 0.5,

            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 0
        }
    },
    "exchanges": {
        "bittrex": {
            "masterkey": "",
            "mastersecret": "",
            "key": "",
            "secret": ""
        },
        "poloniex": {
            "masterkey": "",
            "mastersecret": "",
            "key": "",
            "secret": ""
        },
        "kraken": {
            "masterkey": "",
            "mastersecret": "",
            "key": "",
            "secret": ""
        },
        "cryptopia": {
            "masterkey": "",
            "mastersecret": "",
            "key": "",
            "secret": ""
        },
        "bitfinex": {
            "masterkey": "",
            "mastersecret": "",
            "key": "",
            "secret": ""
        },
        "binance": {
            "masterkey": "",
            "mastersecret": "",
            "key": "",
            "secret": ""
        },
        "cex": {
            "masterkey": "",
            "mastersecret": "",
            "key": "",
            "secret": "",
            "clientId": ""
        },
        "gdax": {
            "masterkey": "",
            "mastersecret": "",
            "key": "",
            "secret": "",
            "passphrase": ""
        }
    },
    "bot": {
        "debug": false,
        "BEST_CURRENCIES": false,
        "BOT_DELAY": 1,
        "BOT_CCLEAN": 2,
        "CANCEL_ORDERS_ENABLED": true,
        "CANCEL_ORDERS_CYCLE_CAP": 1,
        "RESERVE_PILE_UP": false,
        "interval_ticker_update": 25000,
        "period_storage_ticker": 2000,
        "timeout_buy": 60000,
        "timeout_sell": 60000,
        "PYRAMID_BUY": true,
        "TRADING_LIMIT_BUY_PYRAMID": 0.01,
        "TV_GAIN": 0.6,
        "TV_TRADING_LIMIT_BUY": 0.001,
        "TV_TRADING_LIMIT_BUY_PYRAMID": 0.001,
        "TV_PYRAMID": true,
        "TV_TRADING_LIMIT_SELL": 0.001,
        "TV_PROTECTION": false,
        "TV_TRADING_LIMIT_CAP": 0.0001,
        "TV_STOPLOSS_PERCENTAGE": 60,
        "RETRY_TV_ORDER": false,
        "VERBOSE": true,
        "WATCH_MODE": false,
        "MINIMUM_VOLUME_GOOD_CURRENCY": 200,
        "MINIMUM_VARIATION_SUGGEST_TRADE": 1,
        "withdraw_address": "YOURBTCADDRESSHERE",
        "withdraw_threshold": 0.5,
        "TELEGRAM_ENABLED": true,
        "TELEGRAM_NICK": "Gunbot",
        "TOKEN": "YOURTOKENHERE",
        "chat_id": 123456
    },
    "ws": {
        "port": 5001,
        "clientport": 3000,
        "hostname": "127.0.0.1"
    },
    "imap_listener": {
        "enabled": false,
        "authorized_froms": "[\"noreply@tradingview.com\"]",
        "user": "YOUR_EMAIL_HERE",
        "password": "YOUR_PASSWORD_HERE",
        "host": "imap.gmail.com",
        "port": 993,
        "tls": true,
        "tlsOptions": {
            "rejectUnauthorized": false
        }
    }
}
